name: ESLint

on:
  push:
    branches: ['*']

permissions: read-all

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # tag=v6.3.0
        with:
          node-version: 22

      - name: Run ESLint
        run: |
          npm ci
          npm run lint-ci
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463 # tag=v4.36.1
        with:
          sarif_file: build/eslint-results.sarif
          wait-for-processing: true
