name: UnitTests

on:
  push:
    branches: ['*']

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # tag=v6.4.0
        with:
          node-version: 22

      - name: Run tests
        run: |
          npm ci
          npx lerna run prepack
          npm run test-ci
        env:
          TZ: America/Toronto

      - name: Publish test report
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # tag=v6.4.0
        if: always()
        with:
          report_paths: build/junit.xml

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # tag=v1.1.0
        with:
          ref: 'v1.16' # workaround for https://github.com/zgosalvez/github-actions-report-lcov/issues/282

      - name: Publish coverage report
        uses: zgosalvez/github-actions-report-lcov@242badeaf8e48cbad6254e03c270bc80d1a72cc5 # tag=v7.0.8
        with:
          coverage-files: build/lcov.info
          minimum-coverage: 100
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
