name: UnitTests

on:
  push:
    branches: ['*']

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # tag=v7.0.0
        with:
          node-version: 22

      - name: Run tests
        run: |
          npm ci
          npx lerna run prepack
          npm run test-ci
        env:
          TZ: America/Toronto

      - name: Publish test report
        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # tag=v6.4.2
        if: always()
        with:
          report_paths: build/junit.xml

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # tag=v1.1.0
        with:
          ref: 'v1.16' # workaround for https://github.com/zgosalvez/github-actions-report-lcov/issues/282

      - name: Publish coverage report
        uses: zgosalvez/github-actions-report-lcov@00810fe31a127d403ad812ab09e1250e97638b8c # tag=v7.2.0
        with:
          coverage-files: build/lcov.info
          minimum-coverage: 100
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
